apiVersion: v1
kind: Service
metadata:
  name: orderer0
  namespace: org1
spec:
  selector:
    component: orderer0
    type: orderer
  type: ClusterIP
  ports:
    - port: 7050
      targetPort: 7050
