apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderer1
  labels: { component: orderer1, type: orderer, org: orderer }
  namespace: orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: orderer1
      type: orderer
      org: orderer
  template:
    metadata:
      labels:
        component: orderer1
        type: orderer
        org: orderer
    spec:
      volumes:
        - name: orderer-pvc-storage
          persistentVolumeClaim:
            claimName: orderer-pvc-claim
      containers:
        - name: orderer1
          image: hyperledger/fabric-orderer:1.4.3
          resources:
            limits:
              memory: 300Mi
              cpu: "200m"
          ports:
            - containerPort: 7050
          env:
            - name: ORDERER_GENERAL_LISTENADDRESS
              value: "0.0.0.0"
            - name: ORDERER_GENERAL_GENESISMETHOD
              value: file
            - name: ORDERER_GENERAL_GENESISPROFILE
              value: OrdererGenesis
            - name: ORDERER_GENERAL_SYSTEMCHANNEL
              value: syschannel
            - name: ORDERER_GENERAL_GENESISFILE
              value: /var/hyperledger/orderer/data/genesis.block
            - name: ORDERER_GENERAL_LOCALMSPID
              value: orderer
            - name: ORDERER_GENERAL_LOCALMSPDIR
              value: /var/hyperledger/orderer/msp
            - name: ORDERER_GENERAL_TLS_ENABLED
              value: "true"
            - name: ORDERER_GENERAL_TLS_PRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_TLS_CERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_TLS_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
            - name: ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY
              value: /var/hyperledger/orderer/tls/server.key
            - name: ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE
              value: /var/hyperledger/orderer/tls/server.crt
            - name: ORDERER_GENERAL_CLUSTER_ROOTCAS
              value: "[/var/hyperledger/orderer/tls/ca.crt]"
          # command: ["orderer"]
          volumeMounts:
            - mountPath: /var/hyperledger/orderer/msp
              name: orderer-pvc-storage
              subPath: ordererOrgs/orderer.svc.cluster.local/orderers/orderer1.orderer.svc.cluster.local/msp/
            - mountPath: /var/hyperledger/orderer/tls
              name: orderer-pvc-storage
              subPath: ordererOrgs/orderer.svc.cluster.local/orderers/orderer1.orderer.svc.cluster.local/tls/
            - mountPath: /var/hyperledger/production/orderer
              name: orderer-pvc-storage
              subPath: backup/orderers/orderer1/production
            - mountPath: /var/hyperledger/orderer/data
              name: orderer-pvc-storage
              subPath: channel-artifacts
            # - mountPath: /certs
            #   name: host-mount
