apiVersion: v1
kind: Service
metadata:
  name: orderer0
  labels: { component: orderer0, type: orderer, org: orderer }
  namespace: orderer
spec:
  selector:
    component: orderer0
    type: orderer
    org: orderer
  type: ClusterIP
  ports:
    - port: 7050
      targetPort: 7050
