apiVersion: v1
kind: Service
metadata:
  name: orderer1
  labels: { component: orderer1, type: orderer, org: orderer }
  namespace: orderer
spec:
  selector:
    component: orderer1
    type: orderer
    org: orderer
  type: ClusterIP
  ports:
    - port: 7050
      targetPort: 7050
