apiVersion: v1
kind: Service
metadata:
  name: peer0-org1
  namespace: org1
spec:
  selector:
    component: peer0
    type: org1
  ports:
    - port: 7051
      name: peer
      targetPort: 7051
    - port: 7053
      name: event
      targetPort: 7053
