apiVersion: v1
kind: PersistentVolume
metadata:
  name: org2-nfs-volume
  namespace: org2
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: org2-volume
  hostPath:
    path: "/var/k8s-volume"
