apiVersion: apps/v1
kind: Deployment
metadata:
  name: ca-orderer-deployment
  labels: { component: ca, type: ca, org: orderer }
  namespace: orderer
spec:
  replicas: 1
  selector:
    matchLabels:
      component: ca
      type: ca
      org: orderer
  template:
    metadata:
      labels:
        component: ca
        type: ca
        org: orderer
    spec:
      volumes:
        - name: host-mount
          hostPath:
            path: "/host"
        - name: ca-start-script-volume
          configMap:
            name: ca-orderer-start
            defaultMode: 0744
        - name: ca-orderer-configtx
          configMap:
            name: ca-orderer-configtx
      containers:
        - name: ca-orderer
          image: hyperledger/fabric-ca:1.4.3
          resources:
            limits:
              cpu: "100m"
              memory: 1Gi
          volumeMounts:
            - mountPath: /config
              name: host-mount
            - mountPath: /certs
              name: host-mount
            - mountPath: /scripts
              name: ca-start-script-volume
            - mountPath: /configtx
              name: ca-orderer-configtx
          env:
            - name: FABRIC_CA_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_HOME
              value: /etc/hyperledger/fabric-ca-server
            - name: FABRIC_CA_SERVER_CA_NAME
              value: ca-orderer
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
          command: ["sh"]
          args: ["/scripts/start.sh"]
          ports:
            - containerPort: 7054
