apiVersion: v1
kind: Service
metadata:
  name: peer1-org1-couchdb
  labels: { component: peer1, type: couchdb, org: org1 }
  namespace: org1
spec:
  type: ClusterIP
  selector:
    component: peer1
    type: couchdb
    org: org1
  ports:
    - port: 5984
      targetPort: 5984
