apiVersion: v1
kind: Service
metadata:
  name: peer1-org1
  labels: { component: peer, type: clusterip, org: org1 }
  namespace: org1
spec:
  selector:
    component: peer1
    type: peer
    org: org1
  ports:
    - port: 7051
      name: peer
      targetPort: 7051
    - port: 7053
      name: event
      targetPort: 7053
