apiVersion: v1
kind: PersistentVolume
metadata:
  name: org1-nfs-volume
  namespace: org1
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: org1-volume
  hostPath:
    path: "/var/k8s-volume"
