apiVersion: v1
kind: PersistentVolume
metadata:
  name: orderer-nfs-volume
  namespace: orderer
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orderer-volume
  hostPath:
    path: "/var/k8s-volume"
