apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: orderer-pvc-claim
  namespace: orderer
spec:
  storageClassName: orderer-volume
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
