apiVersion: v1
kind: PersistentVolume
metadata:
  name: orderer-nfs-volume
  namespace: orderer
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: orderer-volume
  nfs:
    server: 127.0.0.1
    path: /home/data
