apiVersion: v1
kind: ConfigMap
metadata:
  name: ca-org1-start
  namespace: org1
  labels: { component: ca, type: org1 }
data:
  start.sh: |-
    #!/bin/bash
    set -e
    fabric-ca-server init -b ca-GRID-admin:ca_GRID-adminpw
    mkdir -p /certs/$FABRIC_CA_SERVER_CA_NAME
    cp $FABRIC_CA_SERVER_HOME/ca-cert.pem /certs/$FABRIC_CA_SERVER_CA_NAME/ca-cert.pem
    fabric-ca-server start
  test.sh: |-
    #!/bin/bash
    ls
  ORGS: "['org1']"
