apiVersion: v1
kind: Service
metadata:
  name: peer0-org2-couchdb
  labels: { component: peer0, type: couchdb, org: org2 }
  namespace: org2
spec:
  type: ClusterIP
  selector:
    component: peer0
    type: couchdb
    org: org2
  ports:
    - port: 5984
      targetPort: 5984
